### ISSUE TITLE
Default cognitive to On in skill picker

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/accounts-app#95]
In the skill picker page, after activation of an account please detail the Cognitive option to On.

**Comment by ajefts** [comment]
@vikasrohit Can you do this one Monday?  You can deploy it as soon as it's ready...

**Comment by vikasrohit** [comment]
Okay. Default on means that we have to just show it enabled but actually it is not enabled in backend. It would be enabled only when user hits Save button, right?
Next things is that right now we don't support showing enabled communities in skill picker page because we don't have api to unregister from a member program. So, I have to check if that logic can cause troubles to show enabled button for Cognitive community.

**Comment by ajefts** [comment]
That's correct

**Comment by ajefts** [comment]
Hi @vikasrohit Just wanted to check on your timing for this one.  thanks.

**Comment by vikasrohit** [comment]
I am done with changes, however, few unit tests are failing. Didn't get enough time to fix that today. I would try to close this by tomorrow EOD.

**Comment by ajefts** [comment]
Thanks

**Comment by vikasrohit** [comment]
Deployed to dev. Please let me know if you face any trouble with it. Please note it might not behave as expected if one open the skill picker page  more than once because we are assuming that no one is going to open this page once they have activated their account. We are doing this because we don't have the API for unregister a member from member program.

**Comment by ajefts** [comment]
Looks good.  Can you push it to prod?

**Comment by vikasrohit** [comment]
Done. Deployed to Prod.
